### ISSUE TITLE
Re-implement Stripe integration

### ISSUE THREAD

**Issue by meeh0w** [SkynetLabs/skynet-accounts#157]
## Overview
Since the new Dashboard will be hosted on Skynet (no server side), we need to re-implement the Stripe integration in `skynet-accounts`. Currently there are two routes handled by NextJS in the Skynet Webportal's `dashboard` package:

* [`/billing`](https://github.com/SkynetLabs/skynet-webportal/blob/563e351f8ea2d1d18c21aafcd18d38b8c11b9d2e/packages/dashboard/src/pages/api/stripe/billing.js)
* [`/checkout`](https://github.com/SkynetLabs/skynet-webportal/blob/563e351f8ea2d1d18c21aafcd18d38b8c11b9d2e/packages/dashboard/src/pages/api/stripe/checkout.js)

Additionally to those two, we'll need to be able to query the history of payments:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/3853033/158570613-bc1cde50-5568-482e-9841-603c08a855e1.png">

**Comment by ro-tex** [comment]
I really appreciate the links to the existing scripts. Thanks! 👍
