### ISSUE TITLE
GET /apikeys does not return names

### ISSUE THREAD

**Issue by meeh0w** [SkynetLabs/skynet-accounts#198]
## Describe the bug
`POST /user/apikeys` now supports `name` property, but `GET /user/apikeys` doesn't return it :)

**Comment by ro-tex** [comment]
That's unexpected. When I visit https://account.skynetpro.net/api/user/apikeys I get this JSON:
```json
[
    {
        "id": "6228cecc2e3367f7d2690c21",
        "name": "Ivo's Key",
        "public": "false",
        "skylinks": null,
        "createdAt": "2022-03-09T15:59:08.817Z"
    }
]
```

Is it possible that the update or creation processes somehow fail?

Interestingly, when I tried to call the endpoint from Insomnia, it didn't work. I got some `200 OK` response with a body that contained an old key. But when I did this
```
curl -d '{"name":"say hello to my little curl"}' -H "Content-Type: application/json" -X POST -v --cookie $COOKIE https://account.skynetpro.net/api/user/apikeys
```
it worked like a charm and now the output of my `GET /user/apikeys` is 
```json
[
    {
        "id": "6228cecc2e3367f7d2690c21",
        "name": "Ivo's Key",
        "public": "false",
        "skylinks": null,
        "createdAt": "2022-03-09T15:59:08.817Z"
    },
    {
        "id": "6257f222cb7e9f437b33ea6c",
        "name": "say hello to my little curl",
        "public": "false",
        "skylinks": null,
        "createdAt": "2022-04-14T10:06:26.728Z"
    }
]
```

**Comment by meeh0w** [comment]
Hmm, it's working now. I must have requested data from an outdated service I guess, sorry for the trouble 🙇

**Comment by ro-tex** [comment]
> Hmm, it's working now. I must have requested data from an outdated service I guess, sorry for the trouble 🙇

No problem at all. Next time you see unexpected behaviour you can grab the timestamp and IP of the server you're talking to, so we can check if it's an outdated server or maybe something special is happening there.
