### ISSUE TITLE
Allowlist MySky's skylinks

### ISSUE THREAD

**Issue by ro-tex** [SkynetLabs/skynet-accounts#204]
## Overview

Allowlist the domains from which we want to load MySky:
  - skynet-mysky: AQCsSOIwqwn7lLCT0t110ImQJaI39HxrSrJ-GVNSltfUAQ
  - skynet-mysky-dev: AQBIMqRcHbGWXy4rlIwGW4Aa4v0w0xLb6JvUonnXazfxiw
  - sandbridge: AQASyOUdaov383UggiDN7izfcCH8k-3Z0FlPjtNyem1qMg

**Comment by MSevey** [comment]
Should have mentioned it in the meeting, but let's keep the more inclusive language we've started using elsewhere and call this the allowlist.
